name: PR Verify

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-mergeability:
    name: Check mergeability
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure PR branch is mergeable (no conflicts)
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            // refetch PR to ensure mergeable field is computed
            const { data } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number,
            });
            if (data.mergeable === false) {
              core.setFailed('PR has merge conflicts with the base branch. Please rebase or merge from base.');
            } else {
              core.info(`mergeable=${data.mergeable}`);
            }

  backend-build:
    name: Backend build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install backend deps
        working-directory: server
        run: npm ci

      - name: TypeScript build
        working-directory: server
        run: npm run build


